language: cpp
before_install:
  - mkdir -p ~/bin
  - curl -o ~/bin/yaggo https://github.com/gmarcais/yaggo/releases/download/v1.5.9/yaggo-1.5.9.gem
  - chmod a+rx ~/bin/yaggo
script: autoreconf -i && ./configure YAGGO=~/bin/yaggo && make && make check
